VER_SOCKS5 = 5
ATYP_IPV4, ATYP_DOMAINNAME, ATYP_IPV6 = 1, 3, 4
CMD_CONNECT, CMD_BIND, CMD_UDP_ASSOCIATE = 1, 2, 3
NO_ACCEPTABLE_METHODS = 255
RSV = 0

SOCKS5_GRANTED, SOCKS5_GENERAL_FAILURE, SOCKS5_REJECTED = 0, 1, 2
SOCKS5_NETWORK_UNREACHABLE, SOCKS5_HOST_UNREACHABLE = 3, 4
SOCKS5_CONNECTION_REFUSED, SOCKS5_TTL_EXPIRED = 5, 6
SOCKS5_COMMAND_NOT_SUPPORTED, SOCKS5_ADDRESS_NOT_SUPPORTED = 7, 8
