.TH TORBROWSER-LAUNCHER 1 "MARCH 2014" Linux "User Manuals"
.SH NAME
torbrowser-launcher \- Tor Browser Bundle helper
.SH SYNOPSIS
.B torbrowser-launcher 
.SH DESCRIPTION
.B torbrowser-launcher
is a tool for downloading, verifying, updating and launching the Tor Browser
Bundle.
.SH AUTHOR
Manual page by Jacob Appelbaum <jacob at appelbaum dot net>
.SH "SEE ALSO"
.B tor(1)
